package sprites

const (
	SPRITE_WIDTH_WITH_PADDING = 72
	SPRITE_WIDTH              = 64
	SPRITE_HEIGHT             = 55
	BUILDING_SPRITE_WIDTH_WITH_PADDING = 72
	BUILDING_SPRITE_WIDTH              = 64
	BUILDING_SPRITE_HEIGHT             = 78
)

