package nfo

import "fmt"

type File struct {
	elements []Element
}

func (f *File) AddElement(element Element) {
	if f.elements == nil {
		f.elements = make([]Element, 0)
	}

	f.elements = append(f.elements, element)
}

func (f *File) Output() {
	lines := make([]string, 0)

	for _, el := range f.elements {
		lines = append(lines, el.GetLines()...)
	}

	// Write the header
	fmt.Print("// Automatically generated by GRFCODEC. Do not modify!\n// (Info version 32)\n// Format: spritenum imagefile depth xpos ypos xsize ysize xrel yrel zoom flags\n")
	fmt.Printf("    0 * 4 %s\n", GetDouble(len(lines)))

	for idx, l := range lines {
		fmt.Printf("    %d %s\n", idx + 1, l)
	}
}
